#startup
server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://10.11.11.36:3306/steel_linux?characterEncoding=utf8&useSSL=false
    username: root
    password: cisdi@123456

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

# 执行定时器相关参数配置
job:
  file-path: D:\excel
  template-Path: D:\template
  temp-path:  D:\tmp

#log
logging:
  config: classpath:config/logback-dev.xml

posyspath: e://lic/
popassword: 111111