#startup
server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://10.66.3.221:3306/steel?characterEncoding=utf8&useSSL=true
    username: root
    password: p@ssw0rd

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

# 执行定时器相关参数配置
job:
  file-path: D:\excel
  template-Path: D:\template
  temp-path:  D:\tmp

# 请求的根路径
http:
  url:
   urlApiGLOne: http://10.66.3.202:9001
   urlApiNJOne: http://10.66.3.220:8080
   urlApiJHOne:  http://10.66.3.201:8099
   urlApiYGLOne: http://10.66.3.210:8181
   urlApiSJOne: http://10.66.3.205:9001
   urlApiSJTwo: http://10.66.3.206:9001
#log
logging:
  config: classpath:config/logback-dev.xml

posyspath: e://lic/
popassword: 111111