#startup
server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/steel_linux?characterEncoding=utf8
    username: root
    password: cisdi@123456

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

logging:
  config: classpath:config/logback-dev.xml


# 执行定时器相关参数配置
job:
  file-path: /root/reports
  template-Path: /root/templates
  temp-path: /tmp/templates

posyspath: /root/lic/
popassword: 111111
