#startup
server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://119.84.70.208:3306/steel_wg_data?characterEncoding=utf8&useSSL=false
    username: root
    password: Cisdi@123

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

# 执行定时器相关参数配置
job:
  file-path: C:\project\reportBuild\excel
  template-Path: C:\template
  temp-path:  C:\tmp

#log
logging:
  config: classpath:config/logback-dev.xml

posyspath: e://lic/
popassword: 111111


